<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Monday, 17 February 2025 22:32:59</msg><msg code="2858" type="50">WARNING 002858: Certain rows set to NULL due to error while evaluating python expression: ﻿  File "&lt;string&gt;", line 15, in compare_dH</msg><msg code="539" type="100">ERROR 000539: ﻿Traceback (most recent call last):
﻿  File "&lt;expression&gt;", line 1, in &lt;module&gt;
﻿  File "&lt;string&gt;", line 15, in compare_dH
﻿ValueError: could not convert string to float: '***'
</msg><msg code="-2147467259" type="100">Failed to execute (CalculateField).</msg><msg code="0" type="3">Failed at Monday, 17 February 2025 22:33:00 (Elapsed Time: 0.99 seconds)</msg></messages>