<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Sunday, 19 January 2025 0:26:04</msg><msg code="-2147467259" type="100">﻿Traceback (most recent call last):
﻿  File "E:\git\LevellingThesis\Code\FindLoops.py", line 172, in &lt;module&gt;
﻿    find_loops(levelling_lines_input, source_points_input, loops_type, loops_output)
﻿  File "E:\git\LevellingThesis\Code\FindLoops.py", line 32, in find_loops
﻿    G = create_graph(levelling_lines_input, points_data)
﻿        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿  File "E:\git\LevellingThesis\Code\Utils\Loops.py", line 194, in create_graph
﻿    for row in cursor:
﻿RuntimeError: Cannot find field 'full_name'
</msg><msg code="0" type="0">Failed script Find Loops...</msg><msg code="-2147467259" type="100">Failed to execute (FindLoops).</msg><msg code="0" type="3">Failed at Sunday, 19 January 2025 0:26:05 (Elapsed Time: 0.98 seconds)</msg></messages>