<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Wednesday, 2 July 2025 23:26:47</msg><msg code="0" type="0">Starting the generalization process...</msg><msg code="0" type="0">Classifying points...</msg><msg code="0" type="0">Found 20 junction points, 95 regular points and 12 dead-end points.</msg><msg code="0" type="0">Sorting segments...</msg><msg code="0" type="0">Calling MATLAB function to sort segments...</msg><msg code="1" type="100">MATLAB error: Undefined function 'check_vector_size' for input arguments of type 'double'.
</msg><msg code="0" type="0">MATLAB function call completed.</msg><msg code="-2147467259" type="100">﻿Traceback (most recent call last):
﻿  File "E:\git\LevellingThesis\Code\GeneralizeSegments.py", line 86, in &lt;module&gt;
﻿    generalize_segments(levelling_segments_input, source_points_input, points_classification_output, sorted_segments_output, generalized_lines_output)
﻿  File "E:\git\LevellingThesis\Code\GeneralizeSegments.py", line 28, in generalize_segments
﻿    sorted_segments = sort_segments_matlab_new(levelling_segments_input, source_points_input, junction_points_codes, regular_points_codes, dead_end_points_codes, sorted_segments_output, print_messages = True)
﻿                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿  File "E:\git\LevellingThesis\Code\Utils\Generalization.py", line 417, in sort_segments_matlab_new
﻿    sz1, rows1, cols1 = eng.check_vector_size(vec1, nargout=3)
﻿                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿  File "C:\Users\ilyak\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\matlab\engine\matlabengine.py", line 71, in __call__
﻿    _stderr, feval=True).result()
﻿                         ^^^^^^^^
﻿  File "C:\Users\ilyak\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\matlab\engine\futureresult.py", line 62, in result
﻿    return self.__future.result(timeout)
﻿           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿  File "C:\Users\ilyak\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\matlab\engine\fevalfuture.py", line 76, in result
﻿    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
﻿                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿matlab.engine.MatlabExecutionError: Undefined function 'check_vector_size' for input arguments of type 'double'.

</msg><msg code="0" type="0">Failed script Generalize Segments By Junctions...</msg><msg code="-2147467259" type="100">Failed to execute (GeneralizeSegmentsByJunctions).</msg><msg code="0" type="3">Failed at Wednesday, 2 July 2025 23:27:06 (Elapsed Time: 18.89 seconds)</msg></messages>