<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Wednesday, 7 May 2025 8:09:39</msg><msg code="-2147467259" type="100">﻿Traceback (most recent call last):
﻿  File "E:\git\LevellingThesis\Code\Data Update\FillMissingHeights.py", line 17, in &lt;module&gt;
﻿    calculate_missing_heights(lines_fc, points_fc, known_points_query)
﻿  File "E:\git\LevellingThesis\Code\Utils\Calculations.py", line 351, in calculate_missing_heights
﻿    generalize_sorted_segments(sorted_segments, generalized_lines_output=None, print_messages = False)
﻿  File "E:\git\LevellingThesis\Code\Utils\Generalization.py", line 550, in generalize_sorted_segments
﻿    fill_midpoints_and_dates(generalized_lines, sorted_segments)
﻿  File "E:\git\LevellingThesis\Code\Utils\Generalization.py", line 97, in fill_midpoints_and_dates
﻿    dates = sorted(dates)
﻿            ^^^^^^^^^^^^^
﻿TypeError: '&lt;' not supported between instances of 'NoneType' and 'str'
</msg><msg code="0" type="0">Failed script Fill Missing Heights...</msg><msg code="-2147467259" type="100">Failed to execute (FillMissingHeights).</msg><msg code="0" type="3">Failed at Wednesday, 7 May 2025 9:02:43 (Elapsed Time: 53 minutes 4 seconds)</msg></messages>