<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Saturday, 11 January 2025 8:55:00</msg><msg code="-2147467259" type="100">﻿Traceback (most recent call last):
﻿  File "E:\git\LevellingThesis\Code\GeneralizeSegments.py", line 10, in &lt;module&gt;
﻿    from Utils.Generalization import classify_points, sort_segments, generalize_sorted_segments
﻿  File "E:\git\LevellingThesis\Code\Utils\Generalization.py", line 11, in &lt;module&gt;
﻿    from Utils.Helpers import get_num_of_features, mmyy_int_to_yyyymm_str,start_editing, stop_editing
﻿  File "E:\git\LevellingThesis\Code\Utils\Helpers.py", line 18, in &lt;module&gt;
﻿    from Utils.Generalization import classify_points, sort_segments, generalize_sorted_segments
﻿ImportError: cannot import name 'classify_points' from partially initialized module 'Utils.Generalization' (most likely due to a circular import) (E:\git\LevellingThesis\Code\Utils\Generalization.py)
</msg><msg code="0" type="0">Failed script Generalize Segments...</msg><msg code="-2147467259" type="100">Failed to execute (GeneralizeSegments).</msg><msg code="0" type="3">Failed at Saturday, 11 January 2025 8:55:00 (Elapsed Time: 0.73 seconds)</msg></messages>