<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Saturday, 11 January 2025 8:59:08</msg><msg code="-2147467259" type="100">﻿Traceback (most recent call last):
﻿  File "E:\git\LevellingThesis\Code\FindLoops.py", line 8, in &lt;module&gt;
﻿    from Utils.Helpers import extract_coordinates_from_external_source,start_editing, stop_editing, reverse_line_segments, get_first_segment_with_point, \
﻿ImportError: cannot import name 'extract_coordinates_from_external_source' from 'Utils.Helpers' (E:\git\LevellingThesis\Code\Utils\Helpers.py)
</msg><msg code="0" type="0">Failed script Find Loops...</msg><msg code="-2147467259" type="100">Failed to execute (FindLoops).</msg><msg code="0" type="3">Failed at Saturday, 11 January 2025 8:59:08 (Elapsed Time: 0.39 seconds)</msg></messages>