<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Saturday, 30 August 2025 23:37:40</msg><msg code="-2147467259" type="100">﻿Traceback (most recent call last):
﻿  File "E:\git\LevellingThesis\Code\ResearchToolbox.atbx\ScriptMatlab.tool\tool.script.execute.py", line 12, in &lt;module&gt;
﻿  File "C:\Users\ilyak\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\matlab\engine\__init__.py", line 146, in start_matlab
﻿    eng = future.result()
﻿          ^^^^^^^^^^^^^^^
﻿  File "C:\Users\ilyak\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\matlab\engine\futureresult.py", line 62, in result
﻿    return self.__future.result(timeout)
﻿           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿  File "C:\Users\ilyak\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\matlab\engine\matlabfuture.py", line 87, in result
﻿    handle = pythonengine.getMATLAB(self._future)
﻿             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿matlab.engine.EngineError: Loading C:\Program Files\MATLAB\R2025a\bin\win64\mvm_transport\mvm_transport\mwmvmtransport_layered.dllfailed with error: The specified procedure could not be found.
: state not recoverable: state not recoverable
</msg><msg code="0" type="0">Failed script ScriptMatlab...</msg><msg code="-2147467259" type="100">Failed to execute (ScriptMatlab).</msg><msg code="0" type="3">Failed at Saturday, 30 August 2025 23:37:47 (Elapsed Time: 7.00 seconds)</msg></messages>